import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  console.log("SERVER!");

  const res = await fetch("http://localhost:1337/posts");
  const posts = await res.json();
  console.log(posts);

  return {
    props: { posts },
  };
}

export default function Home({ posts }) {
  console.log("CLIENT!");

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Blog with Strapi API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js Blog with Strapi API</h1>

        <p className={styles.description}>
          Build a Fullstack App with Strapi and Next.js
        </p>

        <div className={styles.grid}>
          {posts &&
            posts.map((post, index) => (
              <Link key={`${post.id}-${index}`} href={`/${post.Slug}`}>
                <a title={post.Title} className={styles.card}>
                  <div className={styles.blur} />
                  <h2 className="post__title">{post.Title}</h2>
                  <span className="post__author">{post.User.username}</span>
                  <p className="post__description">{post.Description}</p>
                </a>
              </Link>
            ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built with{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>{" "}
          <span style={{ paddingLeft: 8, paddingRight: 8 }}>and</span>
          <span className={[styles.logo, { paddingBottom: 4 }]}>
            <Image
              src="/strapi-dark.svg"
              alt="Strapi Logo"
              width={80}
              height={24}
            />
          </span>
        </a>
      </footer>

      <div className="bg" />
    </div>
  );
}
